version: '3.8'

services:
  nginx-xray-proxy:
    image: xiaodouli158/nginx-xray-proxy:latest
    container_name: nginx-xray-proxy
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - PORT=${PORT:-8080}
      - UUID=${UUID:-de04add9-5c68-8bab-950c-08cd5320df18}
      - VMESS_PATH=${VMESS_PATH:-/api/stream/data}
      - VLESS_PATH=${VLESS_PATH:-/api/events/subscribe}
      - LOG_LEVEL=${LOG_LEVEL:-warning}
    volumes:
      - proxy_logs:/app/logs
      - proxy_connections:/app/connections
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  proxy_logs:
  proxy_connections: